### ISSUE TITLE
Missing costs for reputation upgrad gear

### ISSUE THREAD

**Issue by benoakes** [Aleks1015/AtlasLootClassic_Era#17]
**Module:** Faction
**Category:** Argent Dawn, Timbermaw Hold, Thorium Brotherhood
**Loottable:**
**Items:**

**Additional context** All the BOE crafted gear that is upgradable at the faction quartermaster are missing some or all of the costs for the upgrade.  For example the Hardened Black Dragonscale Boots show only the cost in Fireland Embers, but do not show the additional requirement of the Black Dragonscale Boots and 1 Lava Core.

**Comment by Aleks1015** [comment]
@benoakes 

Thanks for your report
It is present, are you looking at the correct version?  Maybe you can paste an example of what you are seeking

![image](https://github.com/user-attachments/assets/9d45d4f4-1bf0-4cb1-9171-292bfed4f902)

**Comment by benoakes** [comment]
Maybe I need to reinstall then. It appears in my game with the icons for Lava Cores and the Boots missing

**Comment by benoakes** [comment]
![image](https://github.com/user-attachments/assets/3206e11a-2b29-43dc-b971-3b6a79319598)

**Comment by benoakes** [comment]
I'm stumped.  I created a new character, disabled all addons except AtlasLoot, and then checked the same pattern. 
![image](https://github.com/user-attachments/assets/1d23fccc-8807-445a-944c-ca1d17977247)

**Comment by Aleks1015** [comment]
Thanks for the screenshot.  I have an idea what may be causing this.

I think it may have to assign a string value the items similar to how the Embers are applied in the code for this.

Will try to have it late tonight.

Thanks!

**Comment by Aleks1015** [comment]
> I'm stumped. I created a new character, disabled all addons except AtlasLoot, and then checked the same pattern. ![image](https://private-user-images.githubusercontent.com/25672045/352853451-1d23fccc-8807-445a-944c-ca1d17977247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTY0NDIsIm5iZiI6MTcyMjI1NjE0MiwicGF0aCI6Ii8yNTY3MjA0NS8zNTI4NTM0NTEtMWQyM2ZjY2MtODgwNy00NDVhLTk0NGMtY2ExZDE3OTc3MjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEyMjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNDQ5NWI2YWU1MDA4YmFjYzQ5NTc0YzdjMzIyNmExNDY0YTc4MDA0NTA5MDMwNzJhOWNjODQ3MTFjN2E0YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HQFVk4SZ2RGCJJrceDWlwkgOKAtrBPMERyUmQ_l9eK8)

I've made some changes and deployed it early this morning along with a small loot table for Ony.  Let me know if this helped!

**Comment by benoakes** [comment]
The icons are still missing with the update.  I tried the Kwonko AtlasLoot and that one has the icons.  Not sure what is different between the two forks.

![image](https://github.com/user-attachments/assets/874b9049-36e7-4151-92a8-52fc5f5da373)

**Comment by Aleks1015** [comment]
> The icons are still missing with the update.  I tried the Kwonko AtlasLoot and that one has the icons.  Not sure what is different between the two forks.
> 
> ![image](https://github.com/user-attachments/assets/874b9049-36e7-4151-92a8-52fc5f5da373)
> 
> 

@benoakes 

Yeah its very odd, it is likely an interaction with another addon.  I will dig a bit further into it later today.

Thanks!

**Comment by Aleks1015** [comment]
@benoakes I think this issue is because of bad data in the cache.  If you exit the game and delete the file for AtlasLoot located in the WTF folder I suspect it may fix the issue.

It would have to be done outside the game or at least in the character screen because when you logout or refresh your UI the wow client will write any settings / variables saved by addons among other things.

I noticed that for some items it stored vendor prices and was able to replicated not the same but a similar issue causing problems with item costs.  After removing it fixed the issue.

I will note that if you have any favourites set AtlasLoot and the location of the minimap icon - this will all reset.

![image](https://github.com/user-attachments/assets/7f0a262a-81c5-49fb-8a2c-881331d2cbff)

**Comment by benoakes** [comment]
Ok I'll try that the next time I'm on

**Comment by benoakes** [comment]
@Aleks1015 Deleting the WTF files did the trick, thanks!
