### ISSUE TITLE
Leatherworking Recipes showing incorrect

### ISSUE THREAD

**Issue by lawmaizing** [Aleks1015/AtlasLootClassic_Era#22]
**Module:** Crafting
**Category:** Leatherworking
**Loottable:** Seasonal P4
**Items:** Devilcore Gauntlets and Devilcore Leggings

**Additional context**

Recipes for the above items are showing incorrect. They are showing incorrect amounts of certain mats e.g. showing 14 devilsaur leather for Legs instead of the intended 20 for SoD, and other mats are missing entirely - specifically the Essence of Fire. 

The current recipes for seasonal Devilcore are as follows:

Devilcore Gauntlets

30 Rugged Leather
8 Devilsaur Leather 
1 Rune Thread
8 Essence of Fire

Devilcore Leggings

30 Rugged Leather
20 Devilsaur Leather
1 Rune Thread
1 Cured Rugged Hide
10 Essence of  Fire

**Comment by Aleks1015** [comment]
Thanks @lawmaizing I've fixed this in version 3.5.21 which I will be deploying shortly.
